# Generated by Django 5.2.9 on 2025-12-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_users', 'Total Users'), ('total_bursaries', 'Total Bursaries'), ('total_applications', 'Total Applications'), ('active_users_today', 'Active Users Today'), ('new_applications_today', 'New Applications Today')], max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('view_bursary', 'View Bursary'), ('apply', 'Submit Application'), ('bookmark', 'Bookmark Bursary'), ('profile_update', 'Profile Update'), ('chat', 'Chat with Bot')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
